# syntax=docker/dockerfile:1

# Build stage - Ubuntu 24.04 con Go
FROM golang:1.26rc2-bookworm AS builder

# Instalar dependencias necesarias para compilar con CGO y SQLite
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

WORKDIR /app/apps/monitoring
RUN go mod download
RUN CGO_ENABLED=1 GOOS=linux go build -o main main.go

# Etapa final - Ubuntu 24.04
FROM ubuntu:24.04

# Evitar prompts interactivos
ENV DEBIAN_FRONTEND=noninteractive

# Instalar SQLite, Docker CLI y certificados SSL
RUN apt-get update && apt-get install -y --no-install-recommends \
    libsqlite3-0 \
    docker.io \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copiar archivos
COPY --from=builder /app/apps/monitoring/main ./main
COPY --from=builder /app/apps/monitoring/main.go ./monitor.go


ENV PORT=3001
EXPOSE 3001

CMD ["./main"]